### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by shingt** [mamoru0217/aibow-ruby#1]
* [ ] ゴルゴのアカウント作成
* 実装
  * [ ] syncのoutgoing_callbackから叩かれるendpoint (POST)
  * それがたたかれてからの処理の実装
    * [ ] メッセージを取得（`content`で取れる？）
    * [ ] メッセージをgo serverに送信してレスポンス取得
    * [ ] ゴルゴのアカウントとしてoauth認証
    * [ ] ゴルゴのアカウントとして先のレスポンスをsync serverにPOST
* [ ] outgoing_callbackの登録（諸々終わったら）
